-- New event types are appended so historic ledger entries remain immutable.
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'PROJECT_PUBLISHED';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'PROJECT_VERSION_PUBLISHED';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'EVENT_PARTICIPATION';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'EVENT_FIRST_PLACE';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'EVENT_SECOND_PLACE';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'EVENT_THIRD_PLACE';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'POSTMARK_SENT';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'POSTMARK_CREDITED_IN_VERSION';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'EVENT_PROJECT_EVALUATED';
ALTER TYPE "ReputationEventType" ADD VALUE IF NOT EXISTS 'ADMIN_ADJUSTMENT';
